### ISSUE TITLE
requirements.txt？？

### ISSUE THREAD

**Issue by kongds1999** [UCSC-VLAA/story-adapter#2]
I am trying to install this environment, but there are some packages in it that I don't know about, as follows:
`# Editable install with no version control (causal-conv1d==1.0.0)`
`-e /home/mjw/Desktop/zigma-main/zigma-main/dis_causal_conv1d`

`# Editable install with no version control (mamba-ssm==1.0.1)`
`-e /home/mjw/Desktop/zigma-main/zigma-main/dis_mamba`

`opensora @ file:///home/mjw/Desktop/Open-Sora-main/Open-Sora`

`selective-scan @ file:///home/mjw/Desktop/VMamba/kernels/selective_scan`

**Comment by jwmao1** [comment]
Thank you very much for your interest in our work, our requirement lists the packages installed for the entire environment. There are many packages that are not necessary for the story-adapter to work, so please just ignore them. Therefore, you just need to make sure that story-adapter is working fine, there is no need to install all the packages in this environment.
