### ISSUE TITLE
能添加Flux.1的模型吗

### ISSUE THREAD

**Issue by czm0304** [UCSC-VLAA/story-adapter#5]
能添加Flux.1的模型吗？如果能添加Flux.1模型，     那么能定义几个角色？    如果用Flux.1模型能不能多个角色同框？

**Comment by jwmao1** [comment]
Thank you for your attention, we are not planning FLUX at this moment, we will plan the deployment of Story-Adapter on FLUX once the paper is accepted. In fact, Story-Adapter already contains some multi-role same-frame results. Take for instance the following two examples:
![github](https://github.com/user-attachments/assets/6412c0c3-70a4-4018-b16f-0644c914c4bb)
![github](https://github.com/user-attachments/assets/96d3a9c5-e0e5-4d9c-a885-22aabc747543)
Thanks again for your questions.
