### ISSUE TITLE
Computational resource requirements of Story-Adapter

### ISSUE THREAD

**Issue by dphero** [UCSC-VLAA/story-adapter#6]
thank you for sharing the code for the paper, I would like to know about the computational resource requirements of Story-Adapter, and under what hardware conditions did you achieve the experimental results in the paper

**Comment by jwmao1** [comment]
Thank you very much for your interest in our work. The device configuration we used was NVIDIA RTX 3090 with an Intel(R) Core(TM) i9-10920X CPU @ 3.50GHz and 128GB of RAM. In fact, Story-Adapter is only needed to fulfill graphics card requirements.
